extends Control


enum Page{
	main, 
	help,
	credits,
}
var page : Page = Page.main
@export var helpScreen : Control
@export var creditsScreen : Control

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	helpScreen.visible = page == Page.help
	creditsScreen.visible = page == Page.credits


func _on_start_button_pressed() -> void:
	get_tree().change_scene_to_file("res://game.tscn")


func _on_continue_button_pressed() -> void:
	pass # Replace with function body.


func _on_how_to_play_pressed() -> void:
	page = Page.help


func _on_highscores_pressed() -> void:
	pass # Replace with function body.


func _on_credits_pressed() -> void:
	page = Page.credits


func _on_back_pressed() -> void:
	page = Page.main
